file1: # fileName
  material: FLINT
  starting-model-data: 100007
  path: "cozyvanilla:item/archaeology_collection/"
  list:
    - "Centurion's Sword"
    - "Centurion's Seal"
    - "Venator Crossbow"
    - "Venator Dagger"
    - "Primis Standard"
    - "Legionary Gladius"
    - "Legionary Shield"
    - "Zaros Effigy"
    - "Hookah Pipe"
    - "Wine Goblet"
    - "Crest of Dagon"
    - "Training Dummy"
    - "Disorder Painting"
    - "Legatus Figurine"
    - "Solem in Umbra Painting"
    - "Imp Mask"
    - "Lesser Demon Mask"
    - "Greater Demon Mask"
    - "Teleportation Crystal"
    - "Ritual Dagger"
    - "Ritual Bell"
    - "Rod of Asclepius"
    - "Chaotic Ewer"
    - "Songbird Recorder"
    - "Frying Pan"
    - "Hallowed Lantern"
    - "Branding Iron"
    - "Manacles"
    - "Ancient Timepiece"
    - "Legatus Pendant"
    - "Ceremonial Ornament"
    - "Dragonkin Device"
    - "Peacock Parasol"
    - "Ceremonial Plume"
    - "Aviansie Dreamcoat"
    - "Strange Totem"
    - "Everlight Harp"
    - "Everlight Trumpet"
    - "Everlight Violin"
    - "Folded-Arm Figurine"
    - "Incite Fear Spell Scroll"
    - "Pontifex Signet Ring"
    - "Curse Tablet"
    - "Dominion Discus"
    - "Dominarian Device"
    - "Fishing Trident"
    - "Herobrine's Book"
    - "Friendship Bracelet"
    - "Urn of Shadow"
    - "Urn of Smoke"
    - "Urn of Blood"
    - "Urn of Ice"
    - "Urn of Miasma"
    - "Hand of the Ancients"
    - "Decorative Amphora"
    - "Loarnab Rod"
    - "Lingam Stone"
    - "Demon's Cube"
    - "Alchemist Flask"
    - "Animate Dead Spell Scroll"
    - "The Lake of Fire Painting"
    - "Inquisitor's Ceremonial Armor"
    - "Inquisitor's Ceremonial Mask"
    - "Inquisitor's Seal"
    - "Gladiator Helmet"
    - "Gladiator Sword"
    - "Model Chariot"
    - "Chaos Star"
    - "Eudoxian Tablet"
    - "Soul Scroll"
    - "Dragon Hook Sword"
    - "Hobgoblin Sword"
    - "Raksha Idol"
    - "Gold Dish"
    - "Xolo Spear"
    - "Ancient Globe"
    - "Spherical Astrolabe"
    - "Tsutsaroth Helm"
    - "Spear of Annihilation"
    - "Praetorian Staff"
    - "Kontos Lance"
    - "Doru Spear"
    - "Tsutsaroth Urumi"
    - "Tsutsaroth Pauldron"
    - "Xolo Hard Hat"
    - "Prototype Godsword"
    - "Prototype Godstaff"
    - "Prototype Godbow"
    - "Night Goggles"
    - "Master Control"
    - "Comfort Gatestone"
    - "The Lord of Light Painting"
    - "Xolo Shield"
    - "Ancient Cooking Pot"
    - "Battle Plans"
    - "War God Sculpture"